version: 2

models: 
  - name: FACTAVERAGECOSTSDLMGZ
    description: Fact Table
    columns:
      - name: FSCLDT_ID
        tests:
        - not_null
        - relationships:
              to: ref('HIERCLNDDLMGZ')
              field: FSCLDT_ID
  - name: FACTTRANSACTIONSDLMGZ
    description: Fact Table
    columns:
      - name: ORDER_ID
        tests:
        - not_null
        - relationships:
              to: ref('HIERRTLLOCDLMGZ')
              field: ORDER_ID
  - name: HIERCLNDDLMGZ
    description: Dimension Table
    columns:
      - name: FSCLDT_ID
        tests:
        - unique
        - not_null
  - name: HIERHLDYDLMGZ
    description: Dimension Table
    columns:
      - name: HLDY_ID
        tests:
        - unique
        - not_null
  - name: HIERINVLOCDLMGZ
    description: Dimension Table
    columns:
      - name: LOC
        tests:
        - unique
        - not_null
  - name: HIERINVSTATUSDLMGZ
    description: Dimension Table
    columns:
      - name: CODE_ID
        tests:
        - unique
        - not_null
  - name: HIERPOSSITEDLMGZ
    description: Dimension Table
    columns:
      - name: SITE_ID
        tests:
        - unique
        - not_null
        
  - name: HIERPRICESTATEDLMGZ
    description: Dimension Table
    columns:
      - name: SUBSTATE_ID
        tests:
        - unique
        - not_null
  - name: HIERPRODDLMGZ
    description: Dimension Table
    columns:
      - name: SKU_ID
        tests:
        - unique
        - not_null
  - name: HIERRTLLOCDLMGZ
    description: Dimension Table
    columns:
      - name: ORDER_ID
        tests:
        - unique
        - not_null

